name: Run Luigi with Linting and Tests

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  luigi-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        pip install black isort flake8

    - name: Lint with black, isort, and flake8
      run: |
        black --check .
        isort --check-only .
        flake8 .

    - name: Run tests
      run: pytest tests

    - name: Run Luigi Task
      run: PYTHONPATH=. luigi --module luigi_pipeline.tasks PrintDateTask --local-scheduler
